### ISSUE TITLE
Raspberry Pi now support clock stretching

### ISSUE THREAD

**Issue by jdimpson** [adafruit/Adafruit-CCS811-Breakout-PCB#1]
Hi! According to [https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/i2c-clock-st](https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/i2c-clock-st), raspberry pi now supports clock stretching as required by this chip. The verbiage in the README.md (an in the adafruit shop link) should probably be updated. Thanks!

**Comment by tannewt** [comment]
Note that clock stretching isn't supported still. The guide page works around it by slowing the i2c clock down. This isn't clock stretching, it's just giving the device more time.

**Comment by kattni** [comment]
@tannewt If that's the case, should the guide page be updated as well to clarify? https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/i2c-clock-stretching

**Comment by ladyada** [comment]
we have
`In order to use certain I2C sensors, such as the BNO055 and the CCS811, you'll need to enable I2C clock stretching 'support' by greatly slowing down the I2C clock on the Raspberry Pi using the device tree overlay.`

**Comment by kattni** [comment]
Ok. I'll update the README.

**Comment by jdimpson** [comment]
Ah, I did not fully appreciate the difference. Thank you. I assume the distinction is that slowing down the i2c clock for this chip slows down everything, which would interfere with any other device in the bus.  That said, the liked article does claim that slowing down the clock will work with this chip, though, which is worth noting. I ordered one last night, so I will try to confirm this.

**Comment by kattni** [comment]
README updated with link to the guide page.

**Comment by caternuson** [comment]
FWIW, i2c-gpio is another option:
https://github.com/adafruit/Adafruit_Blinka/issues/79#issuecomment-622096854

**Comment by jdimpson** [comment]
Based on the outcome of [Issue 4 for the LC709203F Fuel Gauge chip](https://github.com/adafruit/Adafruit_CircuitPython_LC709203F/issues/4) I believe the complete resolution to this issue is that RPi4s do support clock stretching, while any older RPi design does not.
